require('config.barbar')
require('config.colorscheme')
require('config.gitsigns')
require('config.nvim-autopairs')
require('config.nvim-lightbulb')
require('config.treesitter')
require('config.which-key')
